"""added relationship between copperoutput and stock table on voucher

Revision ID: 01866e86d0eb
Revises: 59331709bb98
Create Date: 2026-03-01 11:19:38.803291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01866e86d0eb'
down_revision = '59331709bb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copper_output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_no', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'copper_stock', ['voucher_no'], ['voucher_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copper_output', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('voucher_no')

    # ### end Alembic commands ###
