""" Addition of two columns of amount paid and debt remaining in Copper output table

Revision ID: 213d0c722846
Revises: 8ef07dead9e6
Create Date: 2025-11-08 17:54:52.144767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213d0c722846'
down_revision = '8ef07dead9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copper_output', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('debt_remaining', sa.Float(), nullable=True))

    with op.batch_alter_table('copper_stock', schema=None) as batch_op:
        batch_op.drop_column('out_put')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copper_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('out_put', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('copper_output', schema=None) as batch_op:
        batch_op.drop_column('debt_remaining')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('output_amount')

    # ### end Alembic commands ###
