"""Add cassiterite supplier payment model

Revision ID: 557ef87a0adf
Revises: ac552e555d46
Create Date: 2026-03-01 15:44:01.414434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557ef87a0adf'
down_revision = 'ac552e555d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cassiterite_supplier_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['cassiterite_stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cassiterite_supplier_payment')
    # ### end Alembic commands ###
