"""Add local_balance and total_local_balance to CopperStock

Revision ID: 8ef07dead9e6
Revises: 
Create Date: 2025-10-31 16:53:19.487370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef07dead9e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copper_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rra_3_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('local_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_local_balance', sa.Float(), nullable=True))
        batch_op.drop_column('rra_3percent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('copper_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rra_3percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('total_local_balance')
        batch_op.drop_column('local_balance')
        batch_op.drop_column('rra_3_percent')

    # ### end Alembic commands ###
