"""Add cassiterite module with stock and output tables

Revision ID: ac552e555d46
Revises: 01866e86d0eb
Create Date: 2026-03-01 15:30:21.461284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac552e555d46'
down_revision = '01866e86d0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cassiterite_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('voucher_no', sa.String(length=100), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=False),
    sa.Column('input_kg', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('u', sa.Float(), nullable=True),
    sa.Column('lme', sa.Float(), nullable=True),
    sa.Column('m_lme', sa.Float(), nullable=True),
    sa.Column('sec', sa.Float(), nullable=True),
    sa.Column('tc', sa.Float(), nullable=True),
    sa.Column('u_price', sa.Float(), nullable=True),
    sa.Column('exchange', sa.Float(), nullable=True),
    sa.Column('transport_tag', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('amount_with_taxes', sa.Float(), nullable=True),
    sa.Column('tot_amount_tag', sa.Float(), nullable=True),
    sa.Column('rma', sa.Float(), nullable=True),
    sa.Column('inkomane', sa.Float(), nullable=True),
    sa.Column('rra_3_percent', sa.Float(), nullable=True),
    sa.Column('local_balance', sa.Float(), nullable=True),
    sa.Column('total_local_balance', sa.Float(), nullable=True),
    sa.Column('unit_percent', sa.Float(), nullable=True),
    sa.Column('t_unity', sa.Float(), nullable=True),
    sa.Column('net_balance', sa.Float(), nullable=True),
    sa.Column('total_balance', sa.Float(), nullable=True),
    sa.Column('balance_to_pay', sa.Float(), nullable=True),
    sa.Column('moyenne', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_no')
    )
    op.create_table('cassiterite_output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('output_kg', sa.Float(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=True),
    sa.Column('customer', sa.String(length=100), nullable=True),
    sa.Column('output_amount', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('debt_remaining', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('voucher_no', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['cassiterite_stock.id'], ),
    sa.ForeignKeyConstraint(['voucher_no'], ['cassiterite_stock.voucher_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cassiterite_output', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cassiterite_output_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cassiterite_output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cassiterite_output_batch_id'))

    op.drop_table('cassiterite_output')
    op.drop_table('cassiterite_stock')
    # ### end Alembic commands ###
